# Generated by Django 5.2.11 on 2026-02-15 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_initial'),
        ('organizations', '0003_alter_membership_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['receiver', 'status'], name='idx_invitation_receiver_status'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['organization', 'status'], name='idx_invitation_org_status'),
        ),
    ]
