# Generated by Django 5.2.11 on 2026-02-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictograms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictograms/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pictogram',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
