# Generated by Django 5.2.11 on 2026-03-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictograms', '0002_add_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictogram',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='pictograms/sounds/%Y/%m/%d/'),
        ),
    ]
