# Generated by Django 5.2.11 on 2026-03-25 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_initial'),
        ('pictograms', '0003_pictogram_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictogram',
            name='citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictograms', to='citizens.citizen'),
        ),
    ]
