# Generated by Django 5.2.11 on 2026-04-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture (max 20MB, JPEG/PNG/WebP)', null=True, upload_to='profile_pictures/%Y/%m/%d/'),
        ),
    ]
